import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F0F23",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0F0F23",
  },
  loadingText: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  welcomeSection: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 32,
  },
  welcomeText: {
    fontSize: 26,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 16,
    letterSpacing: -0.5,
    textAlign: "left",
  },
  welcomeSubtext: {
    fontSize: 18,
    color: "#9CA3AF",
    marginTop: 8,
    fontWeight: "500",
    textAlign: "left",
  },
  userStatsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: 20,
  },
  statBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(99, 102, 241, 0.15)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 24,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(99, 102, 241, 0.3)",
  },
  statText: {
    fontSize: 14,
    color: "#6366F1",
    fontWeight: "700",
  },
  newUserBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(236, 72, 153, 0.15)",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(236, 72, 153, 0.3)",
  },
  newUserText: {
    fontSize: 12,
    color: "#EC4899",
    fontWeight: "700",
  },
  quickActionsSection: {
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
    paddingHorizontal: 0,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -0.5,
    textAlign: "left",
    marginBottom: 10,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    justifyContent: "space-between",
  },
  quickActionCard: {
    width: width / 2.45,
    minHeight: 120,
    borderRadius: 20,
    overflow: "hidden",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  quickActionGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  quickActionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "white",
    marginTop: 12,
    textAlign: "center",
  },
  quickActionSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.9)",
    marginTop: 4,
    textAlign: "center",
    fontWeight: "500",
  },
  portfolioSection: {
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  portfolioCard: {
    borderRadius: 24,
    padding: 28,
    borderWidth: 1,
    borderColor: "rgba(99, 102, 241, 0.2)",
    elevation: 12,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  portfolioStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statValue: {
    fontSize: 12,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 8,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  statLabel: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 12,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  statTrend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "rgba(99, 102, 241, 0.1)",
  },
  trendText: {
    fontSize: 10,
    color: "#6366F1",
    fontWeight: "600",
  },
  statDivider: {
    width: 1,
    height: 60,
    backgroundColor: "rgba(99, 102, 241, 0.2)",
    marginHorizontal: 2,
  },
  tipCard: {
    borderRadius: 20,
    padding: 24,
    elevation: 8,
    shadowColor: "#EC4899",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  tipHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  tipTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  tipText: {
    fontSize: 15,
    color: "#FFFFFF",
    lineHeight: 22,
    fontStyle: "italic",
    fontWeight: "500",
  },
  insightsSection: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  achievementsSection: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  newsLoadingContainer: {
    paddingVertical: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  newsLoadingText: {
    fontSize: 15,
    color: "#9CA3AF",
    marginTop: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  newsErrorContainer: {
    paddingVertical: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  newsErrorText: {
    fontSize: 15,
    color: "#9CA3AF",
    marginTop: 16,
    marginBottom: 24,
    fontWeight: "600",
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#6366F1",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    elevation: 4,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  retryButtonText: {
    fontSize: 15,
    color: "white",
    fontWeight: "700",
  },
}); 